# Generated by Django 4.2.2 on 2023-06-18 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pH', models.IntegerField()),
                ('dissolved_oxygen', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('conductivity', models.IntegerField()),
                ('turbidity', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('chlorine', models.IntegerField()),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=20)),
                ('quality_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.qualityanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
