# Generated by Django 4.2.2 on 2023-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_qualityanalysis_qualityresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityresult',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='chlorine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='conductivity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='dissolved_oxygen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='pH',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='tds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='turbidity',
            field=models.FloatField(),
        ),
    ]
