# Generated by Django 4.2.2 on 2023-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_qualityresult_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityresult',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
