# Generated by Django 4.2.2 on 2023-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_alter_qualityresult_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityanalysis',
            name='sample_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
